import { Appointment } from "@/lib/types";

export const appointments: Appointment[] = [
  {
    id: "apt_001",
    patientName: "Aarav Shah",
    patientId: "pat_001",
    doctorName: "Dr. Ananya Rao",
    doctorId: "doc_001",
    clinic: "Qlyno Multispecialty Hospital",
    date: "2026-08-14",
    time: "09:30 AM",
    type: "In-person",
    status: "in-consultation",
    reason: "Routine BP check-up",
  },
  {
    id: "apt_002",
    patientName: "Meera Nambiar",
    patientId: "pat_002",
    doctorName: "Dr. Neha Kulkarni",
    doctorId: "doc_005",
    clinic: "Qlyno Multispecialty Hospital",
    date: "2026-08-14",
    time: "10:00 AM",
    type: "Follow-up",
    status: "waiting",
    reason: "Prenatal follow-up - Week 24",
  },
  {
    id: "apt_003",
    patientName: "Kabir Malhotra",
    patientId: "pat_004",
    doctorName: "Dr. Kavya Iyer",
    doctorId: "doc_003",
    clinic: "Qlyno Multispecialty Hospital",
    date: "2026-08-14",
    time: "10:15 AM",
    type: "In-person",
    status: "confirmed",
    reason: "Fever and cold symptoms",
  },
  {
    id: "apt_004",
    patientName: "Devansh Pandey",
    patientId: "pat_006",
    doctorName: "Dr. Rohan Mehta",
    doctorId: "doc_002",
    clinic: "Qlyno Multispecialty Hospital",
    date: "2026-08-14",
    time: "11:00 AM",
    type: "Follow-up",
    status: "confirmed",
    reason: "Knee replacement follow-up",
  },
  {
    id: "apt_005",
    patientName: "Fatima Ansari",
    patientId: "pat_007",
    doctorName: "Dr. Vikram Nair",
    doctorId: "doc_008",
    clinic: "Qlyno Multispecialty Hospital",
    date: "2026-08-14",
    time: "11:30 AM",
    type: "Video",
    status: "cancelled",
    reason: "Migraine review",
  },
  {
    id: "apt_006",
    patientName: "Ibrahim Sheikh",
    patientId: "pat_003",
    doctorName: "Dr. Simran Kaur",
    doctorId: "doc_007",
    clinic: "Qlyno Multispecialty Hospital",
    date: "2026-08-14",
    time: "12:00 PM",
    type: "In-person",
    status: "completed",
    reason: "Diabetes management",
  },
  {
    id: "apt_007",
    patientName: "Sunita Reddy",
    patientId: "pat_005",
    doctorName: "Dr. Aditya Verma",
    doctorId: "doc_004",
    clinic: "Qlyno Multispecialty Hospital",
    date: "2026-08-15",
    time: "09:00 AM",
    type: "In-person",
    status: "rescheduled",
    reason: "Skin allergy follow-up",
  },
  {
    id: "apt_008",
    patientName: "Aarav Shah",
    patientId: "pat_001",
    doctorName: "Dr. Ananya Rao",
    doctorId: "doc_001",
    clinic: "Qlyno Multispecialty Hospital",
    date: "2026-08-13",
    time: "04:30 PM",
    type: "In-person",
    status: "no-show",
    reason: "ECG review",
  },
];
