import { BillingStaff, LabStaff, Nurse, Receptionist } from "@/lib/types";

export const receptionists: Receptionist[] = [
  {
    id: "rec_001",
    name: "Priya Deshmukh",
    email: "priya.deshmukh@qlyno.health",
    phone: "+91 98200 44112",
    status: "active",
    createdAt: "2023-03-01",
    location: "Qlyno Multispecialty Hospital - Front Desk",
    role: "Receptionist",
    assignedContext: "Clinic",
    branch: "Main Hospital",
    desk: "Front Desk A",
    department: "OPD",
    workflowScope: ["Appointments", "Check-in", "Routing"],
    scope: ["Appointments", "Check-in", "Billing (limited)"],
    appointmentsHandled: 4210,
    avatarUrl: "https://i.pravatar.cc/150?img=5",
  },
  {
    id: "rec_002",
    name: "Sana Sheikh",
    email: "sana.sheikh@qlyno.health",
    phone: "+91 98330 90211",
    status: "active",
    createdAt: "2023-08-19",
    location: "Qlyno Multispecialty Hospital - Front Desk",
    role: "Receptionist",
    assignedContext: "Clinic",
    branch: "Main Hospital",
    desk: "Front Desk B",
    department: "Emergency",
    workflowScope: ["Emergency intake", "Ward routing", "Discharge"],
    scope: ["Appointments", "Check-in", "Patient Registration"],
    appointmentsHandled: 2890,
    avatarUrl: "https://i.pravatar.cc/150?img=9",
  },
  {
    id: "rec_003",
    name: "Manoj Pillai",
    email: "manoj.pillai@qlyno.health",
    phone: "+91 90210 55871",
    status: "invited",
    createdAt: "2024-06-02",
    location: "Qlyno Multispecialty Hospital - Front Desk",
    role: "Receptionist",
    assignedContext: "Clinic",
    branch: "Main Hospital",
    desk: "Front Desk C",
    department: "Admissions",
    workflowScope: ["Appointments"],
    scope: ["Appointments"],
    appointmentsHandled: 0,
    avatarUrl: "https://i.pravatar.cc/150?img=13",
  },
  {
    id: "rec_004",
    name: "Aditi Nair",
    email: "aditi.nair@qlyno.health",
    phone: "+91 98111 75842",
    status: "suspended",
    createdAt: "2022-12-11",
    location: "Qlyno Multispecialty Hospital - Front Desk",
    role: "Receptionist",
    assignedContext: "Clinic",
    branch: "Main Hospital",
    desk: "Front Desk D",
    department: "Diagnostics",
    workflowScope: ["Check-in", "Diagnostics routing"],
    scope: ["Check-in", "Diagnostics"],
    appointmentsHandled: 1840,
    avatarUrl: "https://i.pravatar.cc/150?img=26",
  },
];

export const nurses: Nurse[] = [
  {
    id: "nur_001",
    name: "Anjali Bhosale",
    email: "anjali.bhosale@qlyno.health",
    phone: "+91 99870 12456",
    status: "active",
    createdAt: "2022-09-14",
    location: "Qlyno Multispecialty Hospital - Ward A",
    role: "Nurse",
    level: "Senior Nurse",
    department: "General Ward",
    station: "Station A1",
    shift: "Morning",
    assignedPatients: 12,
    tasksPending: 3,
    tasksOverdue: 0,
    avatarUrl: "https://i.pravatar.cc/150?img=20",
  },
  {
    id: "nur_002",
    name: "Ritu Sharma",
    email: "ritu.sharma@qlyno.health",
    phone: "+91 91234 65890",
    status: "active",
    createdAt: "2023-01-20",
    location: "Qlyno Multispecialty Hospital - ICU",
    role: "Nurse",
    level: "Nurse Lead",
    department: "ICU",
    station: "Station ICU-1",
    shift: "Night",
    assignedPatients: 6,
    tasksPending: 5,
    tasksOverdue: 1,
    avatarUrl: "https://i.pravatar.cc/150?img=21",
  },
  {
    id: "nur_003",
    name: "Zoya Ansari",
    email: "zoya.ansari@qlyno.health",
    phone: "+91 90045 33211",
    status: "active",
    createdAt: "2023-11-08",
    location: "Qlyno Multispecialty Hospital - OPD",
    role: "Nurse",
    level: "Nurse",
    department: "OPD",
    station: "Station P1",
    shift: "Evening",
    assignedPatients: 9,
    tasksPending: 2,
    tasksOverdue: 0,
    avatarUrl: "https://i.pravatar.cc/150?img=23",
  },
  {
    id: "nur_004",
    name: "Kirti Joshi",
    email: "kirti.joshi@qlyno.health",
    phone: "+91 98673 22190",
    status: "on-leave",
    createdAt: "2022-04-17",
    location: "Qlyno Multispecialty Hospital - Ward B",
    role: "Nurse",
    level: "Nurse",
    department: "General Ward",
    station: "Station A2",
    shift: "Morning",
    assignedPatients: 0,
    tasksPending: 0,
    tasksOverdue: 0,
    avatarUrl: "https://i.pravatar.cc/150?img=24",
  },
];

export const billingStaff: BillingStaff[] = [
  {
    id: "bil_001",
    name: "Suresh Kamble",
    email: "suresh.kamble@qlyno.health",
    phone: "+91 99200 77123",
    status: "active",
    createdAt: "2022-05-11",
    location: "Qlyno Multispecialty Hospital - Billing Desk",
    role: "Billing Staff",
    scopes: ["OPD Billing", "Insurance/TPA"],
    collectionsToday: 84500,
    pendingInvoices: 14,
    avatarUrl: "https://i.pravatar.cc/150?img=33",
  },
  {
    id: "bil_002",
    name: "Neelam Gupta",
    email: "neelam.gupta@qlyno.health",
    phone: "+91 98120 44567",
    status: "active",
    createdAt: "2023-02-27",
    location: "Qlyno Multispecialty Hospital - Billing Desk",
    role: "Billing Staff",
    scopes: ["OPD Billing", "Refund Desk"],
    collectionsToday: 52300,
    pendingInvoices: 9,
    avatarUrl: "https://i.pravatar.cc/150?img=36",
  },
];

export const labStaffList: LabStaff[] = [
  {
    id: "lab_001",
    name: "Dr. Meera Kapoor",
    email: "meera.kapoor@qlyno.health",
    phone: "+91 98900 12321",
    status: "active",
    createdAt: "2021-10-04",
    location: "Qlyno Multispecialty Hospital - Diagnostics",
    role: "Pathologist",
    labLocation: "Qlyno Multispecialty Hospital - Diagnostics",
    ordersHandled: 5620,
    avatarUrl: "https://i.pravatar.cc/150?img=41",
  },
  {
    id: "lab_002",
    name: "Rakesh Yadav",
    email: "rakesh.yadav@qlyno.health",
    phone: "+91 90045 87654",
    status: "active",
    createdAt: "2022-12-19",
    location: "Qlyno Multispecialty Hospital - Diagnostics",
    role: "Lab Technician",
    labLocation: "Qlyno Multispecialty Hospital - Diagnostics",
    ordersHandled: 3210,
    avatarUrl: "https://i.pravatar.cc/150?img=53",
  },
  {
    id: "lab_003",
    name: "Ayesha Khan",
    email: "ayesha.khan@qlyno.health",
    phone: "+91 91234 09876",
    status: "active",
    createdAt: "2023-07-30",
    location: "Qlyno Multispecialty Hospital - Diagnostics",
    role: "Collection Agent",
    labLocation: "Qlyno Multispecialty Hospital - Diagnostics",
    ordersHandled: 1180,
    avatarUrl: "https://i.pravatar.cc/150?img=44",
  },
];
